### 판다스
- 판다스는 구조화된 데이터 형식을 제공. 시리즈는 1차원 배열, 데이터 프레임은 2차원 배열
- 라이브러리는 여러종류의 class와 내장 함수로 구성. 시리즈와 데이터 프레임은 대표적인 클래스 객체임
- 시리즈 인덱스는 데이터 값과 1대1 대응, 파이썬 딕셔너리와 비슷한 구조.pandas.Series(딕셔너리)
- Content
    - Series(변화느 인덱스 구조, 원소 선택) Culumn 이름 없음
    - DataFrame(변환, 행인덱스/열이름 지정, 삭제, 선택, 추가, 변경, 전치, 인덱스 활용) Culumn 이름 있음

In [13]:
# 시리즈 클래스 만들기
# pandas 불러오기 (pd)
import pandas as pd

# key : value 구조를 갖는 딕셔너리를 만들고 변수 dict_data에 저장
dict_data = {'a':1,'b':2,'c':3}

sr = pd.Series(dict_data)
sr

a    1
b    2
c    3
dtype: int64

In [14]:
# 리스트를 시리즈로 변환
import pandas as pd

list_data = ['2019-07-02',3.14,'ABC',100,True]
st = pd.Series(list_data, index=list('abcde'))
st

a    2019-07-02
b          3.14
c           ABC
d           100
e          True
dtype: object

In [15]:
# 인덱스 및 값
idx = sr.index
val = sr.values
print(idx)
print(val)

Index(['a', 'b', 'c'], dtype='object')
[1 2 3]


In [16]:
# 튜플을 시리즈로 변환
tup_data = ('신인철','2019-07-02','님',True)
# list_data = []
# dict_data = {}
sr = pd.Series(tup_data, index =['이름','생년월일','성별','학생여부'])
print(sr)

이름             신인철
생년월일    2019-07-02
성별               님
학생여부          True
dtype: object


In [17]:
# 인덱싱
print(sr[0]) # index Num으로 불러오기
print(sr['이름']) # index 명으로 불러오기
print(sr[[1,2]]) #index num(리스트) 형태로 불러오기

신인철
신인철
생년월일    2019-07-02
성별               님
dtype: object


In [18]:
import numpy as np

s1 = np.arange(11,21,2)
print(s1,type(s1))

s2 = pd.Series(s1,index= list('abcde'))
print(s2, type(s2))

[11 13 15 17 19] <class 'numpy.ndarray'>
a    11
b    13
c    15
d    17
e    19
dtype: int64 <class 'pandas.core.series.Series'>


만약에 함수() 괄호 내에 요소가 궁금하면
함수() 괄호 안에  shift+tab 2번 누르면 요소 종류 나옴

In [19]:
import pandas as pd
import numpy as np
num = np.arange(1000,5000,1000)
state = ['Califonia','Ohio','Oregon','Texas']
result = pd.Series(num,index=state) # Series의 객체
result.name = 'population' #result 출력 후에 name : population 추가 / 해당 객체 이름
result.index.name = 'state' #index 위에 이름 / 전체 객체에 이름 추가
print(result)

state
Califonia    1000
Ohio         2000
Oregon       3000
Texas        4000
Name: population, dtype: int64


In [20]:
result.Califonia = np.nan # califonia 에 null값 입력
result

state
Califonia       NaN
Ohio         2000.0
Oregon       3000.0
Texas        4000.0
Name: population, dtype: float64

In [21]:
result.isnull().sum()# null값 유무 확인 /.sum() 참 값만 더해서 출력

1

### 데이터프레임
- 데이터프레임은 2차원 배열, R의 데이터프레임에서 유래.
- 데이터프레임의 열은 각각 시리즈 개체.
- 시리즈를 열벡터라고 하면 데이터프레임은 여러 개의 열벡터들이 같은 행 인덱스를  
기준으로 줄지어 결합된 2차원 벡터 또는 행렬
- 선형대수학에서 열벡터(m x 1 행렬)는 m 원소들의 단일 열 행렬
- 행 벡터(1 x m행렬)은 m 원소들의 단일 행 행렬
- 리스트, 딕셔너리, ndarray 등 다양한 데이터로 부터 생성
- 반대로 리스트, 딕셔너리, ndarray 등으로 변환 될 수 있음

In [22]:
# 배열을 데이터 프레임으로 변환
import numpy as np
np.random.seed(0) #출력된 값 고정
data = np.random.randint(100,120,size=(3,3)) # 3 x 3 사이즈의 범위 내 랜덤 정수 출력
print(data,type(data))

df = pd.DataFrame(data,index=['d1','d2','d3'],columns=['pd','sales','inv'])
df

[[112 115 100]
 [103 103 107]
 [109 119 118]] <class 'numpy.ndarray'>


pd  sales  inv
d1  112    115  100
d2  103    103  107
d3  109    119  118

In [23]:
#pandas indexing : iloc 정수 인덱스, loc 이름 인덱스

print(df.iloc[1],'\n')
print(df.loc['d2'],'\n')
print(df.iloc[1][1],'\n')
print(df.loc['d2','sales'],'\n')

pd       103
sales    103
inv      107
Name: d2, dtype: int64 

pd       103
sales    103
inv      107
Name: d2, dtype: int64 

103 

103 



In [24]:
df.loc['d3'] = 0
df

pd  sales  inv
d1  112    115  100
d2  103    103  107
d3    0      0    0

In [25]:
df.loc['d4'] = 0
df

pd  sales  inv
d1  112    115  100
d2  103    103  107
d3    0      0    0
d4    0      0    0

In [26]:

id = np.arange(1,1001)
i1 = pd.Series(id)
gender = np.random.randint(2,size=1000)
g = pd.Series(gender)
age = np.random.randint(1,101,size = 1000)
a = pd.Series(age)
region = np.random.randint(1,11,size = 1000)
r = pd.Series(region)

df = pd.concat([i1,g,a,r],axis=1) #concat 합치기 list 형태로 / axis = 행 = 0 열 = 1 / 입력 안하면 기본 0
df.rename(columns={0:'id',1:'gender',2:'age',3:'region'}, inplace=True) #컬럼 이름명 바꾸기 inplace=True 원본을 바꾸는지
df

id  gender  age  region
0       1       0   11      10
1       2       1   68      10
2       3       0    7       7
3       4       0   92      10
4       5       0  100      10
..    ...     ...  ...     ...
995   996       0   73       8
996   997       1    6       4
997   998       1   40       6
998   999       0   80       7
999  1000       0   80       5

[1000 rows x 4 columns]

In [27]:
# 과제
# 위 데이터에 적합한 컬럼 5개를 추가하여 출력하세요 /생년월일,
data1 = np.random.randint(1940,2022,size=1000)
dat1 = pd.Series(data1)
data2 = np.random.randint(1,13,size=1000)
dat2 = pd.Series(data2)
data3 = np.random.randint(1,32,size=1000)
dat3 = pd.Series(data3)
data4 = np.random.randint(3,7,size=1000)
dat4 = pd.Series(data4)
data5 = np.random.randint(2,size=1000)
dat5 = pd.Series(data5)
df_z = pd.concat([df,dat1,dat2,dat3,dat4,dat5],axis=1)
df_z.rename(columns={0:'b_year',1:'b_month',2:'b_day',3:'local',4:'ms'},inplace=True)
print(df_z)


       id  gender  age  region  b_year  b_month  b_day  local  ms
0       1       0   11      10    2013        3     12      5   0
1       2       1   68      10    1964       10     19      6   1
2       3       0    7       7    1987        2     12      4   1
3       4       0   92      10    1972       11      7      4   0
4       5       0  100      10    2014       12     23      4   0
..    ...     ...  ...     ...     ...      ...    ...    ...  ..
995   996       0   73       8    1980        8     19      5   0
996   997       1    6       4    1980        2     28      5   1
997   998       1   40       6    1947        1     21      4   1
998   999       0   80       7    1966       11     16      3   1
999  1000       0   80       5    1969       12     30      3   1

[1000 rows x 9 columns]


In [28]:
#df1 = df[:] # df를 복사해서 사용
df1 = df.copy() # df를 복사해서 사용
#df1.head(3) # 숫자를 입력한 만큼 나옴 기본 5개
df1.tail(3) # 숫자를 입력한 만큼 뒤에서 x개 만큼 나옴 기본 5개

id  gender  age  region
997   998       1   40       6
998   999       0   80       7
999  1000       0   80       5

In [29]:
df1.iloc[:2] = np.nan #0~2까지 Null 값을 입력
df1.head()

id  gender    age  region
0  NaN     NaN    NaN     NaN
1  NaN     NaN    NaN     NaN
2  3.0     0.0    7.0     7.0
3  4.0     0.0   92.0    10.0
4  5.0     0.0  100.0    10.0

In [30]:
a = np.random.randint(1,5,size=(10,5))
print(a)

[[1 1 4 3 3]
 [2 2 1 1 4]
 [2 4 3 3 1]
 [4 4 1 3 2]
 [1 1 1 1 1]
 [1 3 3 4 2]
 [3 4 3 4 2]
 [4 1 3 3 4]
 [2 2 3 1 1]
 [2 4 4 2 1]]


In [31]:
# 2차원 리스트를 데이터프레임으로 변환
list1 = a.tolist() # 배열을 리스트로 변환
print(list1,type(list1))

df1 = pd.DataFrame(list1, columns=['c1','c2','c3','c4','c5'])
print(df1.head(3))

[[1, 1, 4, 3, 3], [2, 2, 1, 1, 4], [2, 4, 3, 3, 1], [4, 4, 1, 3, 2], [1, 1, 1, 1, 1], [1, 3, 3, 4, 2], [3, 4, 3, 4, 2], [4, 1, 3, 3, 4], [2, 2, 3, 1, 1], [2, 4, 4, 2, 1]] <class 'list'>
   c1  c2  c3  c4  c5
0   1   1   4   3   3
1   2   2   1   1   4
2   2   4   3   3   1


In [32]:
#데이터 프레임을 배열, 라스트, 딕셔너리로 변환 
ar = df1.values #데이터 프레임을 배열로 변환
print(ar,type(ar))

li = ar.tolist() #배열을 리스트로 변환
print(li,type(li))

dict = df1.to_dict('list') # 데이터 프레임을 넣어서 딕셔너리로 변환
print(dict,type(dict))

[[1 1 4 3 3]
 [2 2 1 1 4]
 [2 4 3 3 1]
 [4 4 1 3 2]
 [1 1 1 1 1]
 [1 3 3 4 2]
 [3 4 3 4 2]
 [4 1 3 3 4]
 [2 2 3 1 1]
 [2 4 4 2 1]] <class 'numpy.ndarray'>
[[1, 1, 4, 3, 3], [2, 2, 1, 1, 4], [2, 4, 3, 3, 1], [4, 4, 1, 3, 2], [1, 1, 1, 1, 1], [1, 3, 3, 4, 2], [3, 4, 3, 4, 2], [4, 1, 3, 3, 4], [2, 2, 3, 1, 1], [2, 4, 4, 2, 1]] <class 'list'>
{'c1': [1, 2, 2, 4, 1, 1, 3, 4, 2, 2], 'c2': [1, 2, 4, 4, 1, 3, 4, 1, 2, 4], 'c3': [4, 1, 3, 1, 1, 3, 3, 3, 3, 4], 'c4': [3, 1, 3, 3, 1, 4, 4, 3, 1, 2], 'c5': [3, 4, 1, 2, 1, 2, 2, 4, 1, 1]} <class 'dict'>


In [33]:
# file 생성
file_data = pd.DataFrame({
    'col1':[1,2,3,4,5,6],
    'col2':['A','A','B','B','C','C']
})
print(file_data)

   col1 col2
0     1    A
1     2    A
2     3    B
3     4    B
4     5    C
5     6    C


In [34]:
file_data.to_csv('dataset/file_data.csv', index=None) #csv 파일로 저장
file_data = pd.read_csv('dataset/file_data.csv')
print(file_data,type(file_data))

   col1 col2
0     1    A
1     2    A
2     3    B
3     4    B
4     5    C
5     6    C <class 'pandas.core.frame.DataFrame'>


In [35]:
#딕셔너리
df_1 = pd.DataFrame({
    'col1' : np.array([1,2,3]),
    'col2' : np.array(['A','B','C'])
})
df_2 = pd.DataFrame({
    'col1' : np.array([4,5,6]),
    'col2' : np.array(['D','E','F'])
})

df_3 =pd.concat([df_1,df_2],axis=1)
df_4 =pd.concat([df_1,df_2])
print(df_3)
print(df_4)

   col1 col2  col1 col2
0     1    A     4    D
1     2    B     5    E
2     3    C     6    F
   col1 col2
0     1    A
1     2    B
2     3    C
0     4    D
1     5    E
2     6    F


In [36]:
# 데이터 추출
print(df_4['col2']) #col2만 출력 (시리즈)

df= pd.DataFrame(df_4.col2) #df_4.col2(시리즈)를 데이터 프레임으로 불러온다
df_f= pd.DataFrame(df_4['col2'])
print(type(df))
print(type(df_f))
df_4[['col1','col2']] #대괄호 안에 리스트 형태로 넣으면 시리즈에서 데이터프레임으로 출력가능

0    A
1    B
2    C
0    D
1    E
2    F
Name: col2, dtype: object
<class 'pandas.core.frame.DataFrame'>
<class 'pandas.core.frame.DataFrame'>


col1 col2
0     1    A
1     2    B
2     3    C
0     4    D
1     5    E
2     6    F

In [305]:
#열 삭제
df = df1.copy()
df_a = df.drop('c1',axis=1) #줄을 다 지우는 함수 drop(,axis)

KeyError: "['c1'] not found in axis"

In [38]:
#첫 행만 출력
df.query('c3==3') #쿼리 조건문 c3 column이 3인 것만 출력

c1  c2  c3  c4  c5
2   2   4   3   3   1
5   1   3   3   4   2
6   3   4   3   4   2
7   4   1   3   3   4
8   2   2   3   1   1

In [39]:
df.query('c3==2 & c4==2')

Empty DataFrame
Columns: [c1, c2, c3, c4, c5]
Index: []

In [40]:
df.query('c3==2 | c4==2')

c1  c2  c3  c4  c5
9   2   4   4   2   1

In [41]:
df.query('c3==3')[['c3','c4']] # c3,c4 에서 c3가 3인 것

c3  c4
2   3   3
5   3   4
6   3   4
7   3   3
8   3   1

In [42]:
help(df.query) #쿼리 도움말

Help on method query in module pandas.core.frame:

query(expr, inplace=False, **kwargs) method of pandas.core.frame.DataFrame instance
    Query the columns of a DataFrame with a boolean expression.
    
    Parameters
    ----------
    expr : str
        The query string to evaluate.
    
        You can refer to variables
        in the environment by prefixing them with an '@' character like
        ``@a + b``.
    
        You can refer to column names that are not valid Python variable names
        by surrounding them in backticks. Thus, column names containing spaces
        or punctuations (besides underscores) or starting with digits must be
        surrounded by backticks. (For example, a column named "Area (cm^2) would
        be referenced as `Area (cm^2)`). Column names which are Python keywords
        (like "list", "for", "import", etc) cannot be used.
    
        For example, if one of your columns is called ``a a`` and you want
        to sum it with ``b``, your quer

In [43]:
df.rename(columns={'c1':'국어','c2':'영어','c3':'수학','c4':'과학','c5':'체육'},inplace=True)
df

국어  영어  수학  과학  체육
0   1   1   4   3   3
1   2   2   1   1   4
2   2   4   3   3   1
3   4   4   1   3   2
4   1   1   1   1   1
5   1   3   3   4   2
6   3   4   3   4   2
7   4   1   3   3   4
8   2   2   3   1   1
9   2   4   4   2   1

In [44]:
import warnings
warnings.filterwarnings('ignore')
df_e = df[:3] #df의 3번째 행까지 
df_e.rename(index={0:'홍길동',1:'김땡땡',2:'김인직'},inplace=True)
df_e

국어  영어  수학  과학  체육
홍길동   1   1   4   3   3
김땡땡   2   2   1   1   4
김인직   2   4   3   3   1

In [45]:
df_e.loc['홍길동','과학'] #컬럼, 인덱스 명으로 찾기
df_e.iloc[0,4] # 인덱스 넘버로 찾기

3

In [46]:
#사전으로 데이터프레임 생성
ds_1 = pd.DataFrame({
    'col1' : np.array([1,2,3,4,5,6,7,8]),
    'col2' : np.array([8,7,6,5,4,3,2,1]),
    'col3' : np.array([1,2,3,4,5,6,7,8]),
    'col4' : np.array([8,7,6,5,4,3,2,1]),
    'col5' : np.array([1,2,3,4,5,6,7,8])
})
ds_1

col1  col2  col3  col4  col5
0     1     8     1     8     1
1     2     7     2     7     2
2     3     6     3     6     3
3     4     5     4     5     4
4     5     4     5     4     5
5     6     3     6     3     6
6     7     2     7     2     7
7     8     1     8     1     8

In [60]:
ar_data = np.random.randint(1,157,size=(8,5))
ar = pd.DataFrame(ar_data,)

array([[ 20,  79,  39,  38,  36],
       [ 12, 103,  43,  42,  79],
       [ 41, 115,  56,  35,  32],
       [148,  58, 102,  24,  77],
       [ 81,  98,  31,  92, 132],
       [ 87, 130,  15, 156, 129],
       [ 10,  36,  79,  33, 155],
       [ 13,  53,  79,  20,  94]])

In [47]:
#생성된 데이터 프레임에서 아래 사항을 수행하세요




In [48]:
#열 이름과 행 이름 변경
ds_1.rename(
columns={'col1':'월','col2':'화','col3':'수','col4':'목','col5':'금'},
index={0:'1교시',1:'2교시',2:'3교시',3:'4교시',4:'5교시',5:'6교시',6:'7교시',7:'8교시',}
,inplace=True)
ds_1

월  화  수  목  금
1교시  1  8  1  8  1
2교시  2  7  2  7  2
3교시  3  6  3  6  3
4교시  4  5  4  5  4
5교시  5  4  5  4  5
6교시  6  3  6  3  6
7교시  7  2  7  2  7
8교시  8  1  8  1  8

In [49]:
#3행만 출력
ds_1[:2]

월  화  수  목  금
1교시  1  8  1  8  1
2교시  2  7  2  7  2

In [50]:
#5열만 출력
ds_1.금


1교시    1
2교시    2
3교시    3
4교시    4
5교시    5
6교시    6
7교시    7
8교시    8
Name: 금, dtype: int64

In [51]:
#3행 5열의 값 출력
ds_1.금[2]


3

In [66]:
ds_1.loc['2교시']['금']

2

In [52]:
#4열의 값을 모두 0으로 변경
ds_1.iloc[3] = 0
ds_1


월  화  수  목  금
1교시  1  8  1  8  1
2교시  2  7  2  7  2
3교시  3  6  3  6  3
4교시  0  0  0  0  0
5교시  5  4  5  4  5
6교시  6  3  6  3  6
7교시  7  2  7  2  7
8교시  8  1  8  1  8

In [53]:
# 2,3행의 3열 값을 조회(2가지 방법)(iloc,loc)
print(ds_1.iloc[1:3,2])
print(ds_1.loc['2교시':'3교시','수'])


2교시    2
3교시    3
Name: 수, dtype: int64
2교시    2
3교시    3
Name: 수, dtype: int64


In [54]:
# 6행의 2,3,4열의 값을 조회(2가지 방법)(iloc,loc)
print(ds_1.iloc[5,1:5])
print(ds_1.loc['6교시','화':'금'])


화    3
수    6
목    3
금    6
Name: 6교시, dtype: int64
화    3
수    6
목    3
금    6
Name: 6교시, dtype: int64


In [55]:
# 2열을 Series와 DataFrame으로 각각 출력
dt = pd.DataFrame(ds_1.화)
print(dt,type(dt))

print(ds_1.화,type(ds_1.화))


     화
1교시  8
2교시  7
3교시  6
4교시  0
5교시  4
6교시  3
7교시  2
8교시  1 <class 'pandas.core.frame.DataFrame'>
1교시    8
2교시    7
3교시    6
4교시    0
5교시    4
6교시    3
7교시    2
8교시    1
Name: 화, dtype: int64 <class 'pandas.core.series.Series'>


In [56]:
# 2행 3열의 값을 2행 4열의 값과 동일하게 변경
ds_1.iloc[1,2] = ds_1.iloc[1,3]
ds_1


월  화  수  목  금
1교시  1  8  1  8  1
2교시  2  7  7  7  2
3교시  3  6  3  6  3
4교시  0  0  0  0  0
5교시  5  4  5  4  5
6교시  6  3  6  3  6
7교시  7  2  7  2  7
8교시  8  1  8  1  8

In [59]:
# 2행 3열의 값과 2행 4열의 값을 동시에 만족하는 3,4열을 출력(query)
ds_1.query('index == "2교시" & 수 == 목')[['수','목']]

수  목
2교시  7  7

In [69]:
ds_1.query('index == "2교시"')[['수','목']]

수  목
2교시  7  7

In [71]:
ds_1.iloc[[1]].query('수 == 목')[['수','목']]

수  목
2교시  7  7

In [359]:
data1 = np.random.randint(1940,2022,size=1000)
dat1 = pd.Series(data1)
data2 = np.random.randint(1,13,size=1000)
dat2 = pd.Series(data2)
data3 = np.random.randint(1,32,size=1000)
dat3 = pd.Series(data3)
data4 = np.random.randint(3,7,size=1000)
dat4 = pd.Series(data4)
data5 = np.random.randint(2,size=1000)
dat5 = pd.Series(data5)
df_z = pd.concat([df,dat1,dat2,dat3,dat4,dat5],axis=1)
df_z.rename(columns={0:'b_year',1:'b_month',2:'b_day',3:'local',4:'ms'},inplace=True)
print(df_z)

       id  gender  age  region  b_year  b_month  b_day  local  ms
0       1       1    9       6    1947        3     28      4   1
1       2       1   48      10    2001       11     23      6   0
2       3       1    2       3    1997        3     18      4   0
3       4       0   90       6    1971        3     25      4   0
4       5       0   34       4    1965        7     22      6   1
..    ...     ...  ...     ...     ...      ...    ...    ...  ..
995   996       1   97       9    2021       12     10      6   1
996   997       1   47       8    1959       10      6      4   1
997   998       1   87       8    1941        1      4      6   0
998   999       1   56       3    1978       12     27      5   0
999  1000       1   65       5    1945       12     26      6   1

[1000 rows x 9 columns]


In [72]:
np.random.seed(0)
data = np.random.randint(80,100,size=(5,5))
df = pd.DataFrame(data, columns=list('abcde'))
df

a   b   c   d   e
0  92  95  80  83  83
1  87  89  99  98  84
2  86  92  81  86  87
3  94  97  85  93  88
4  89  99  96  99  85

In [73]:
df1 = df.copy()
df1

a   b   c   d   e
0  92  95  80  83  83
1  87  89  99  98  84
2  86  92  81  86  87
3  94  97  85  93  88
4  89  99  96  99  85

In [74]:
df1['index'] = list('가나다라마')
df1

a   b   c   d   e index
0  92  95  80  83  83     가
1  87  89  99  98  84     나
2  86  92  81  86  87     다
3  94  97  85  93  88     라
4  89  99  96  99  85     마

In [75]:
df1['f'] = [80,81,82,83,84]
df1

a   b   c   d   e index   f
0  92  95  80  83  83     가  80
1  87  89  99  98  84     나  81
2  86  92  81  86  87     다  82
3  94  97  85  93  88     라  83
4  89  99  96  99  85     마  84

In [77]:
df2 = df1.set_index('index') #set_index 를 이용해 앞에서 추가 가능
df2

a   b   c   d   e   f
index                        
가      92  95  80  83  83  80
나      87  89  99  98  84  81
다      86  92  81  86  87  82
라      94  97  85  93  88  83
마      89  99  96  99  85  84

In [107]:
df3 = df2.reset_index() #index가 행의 제일 앞에서 뒤로 한칸 밀려남
df3

level_0 index   a   b   c   d   e   f
0        0     가  92  95  80  83  83  80
1        1     나  87  89  99  98  84  81
2        2     다  86  92  81  86  87  82
3        3     라  94  97  85  93  88  83
4        4     마  89  99  96  99  85  84

In [110]:
df1 = df3[['a','b','c','d','e','index']] #컬럼 순서를 원하는대로 바꾸기
df1

a   b   c   d   e index
0  92  95  80  83  83     가
1  87  89  99  98  84     나
2  86  92  81  86  87     다
3  94  97  85  93  88     라
4  89  99  96  99  85     마

In [121]:
# 문제
# 딕셔너리로 데이터 프레임을 (5행5열)작성
#index = ['r0','r1','r2','r3','r4']
#column = list('abcde')
index = ['r0','r1','r2','r3','r4']
column = list('abcde')
dic_data = {'a':[1,2,3,4,5],'b':[1,2,3,4,5],'c':[1,2,3,4,5],'d':[1,2,3,4,5],'e':[1,2,3,4,5]}

df = pd.DataFrame(dic_data, index=['r0','r1','r2','r3','r4'])
df


a  b  c  d  e
r0  1  1  1  1  1
r1  2  2  2  2  2
r2  3  3  3  3  3
r3  4  4  4  4  4
r4  5  5  5  5  5

In [120]:
# df['r5'] = [0,0,0,0,0] #열을 추가할때
# df['r6'] = [0,0,0,0,0]
df.loc['r5'] = 0
df.loc['r6'] = 0
df

a  b  c  d  e  r5  r6
r0  1  1  1  1  1   0   0
r1  2  2  2  2  2   0   0
r2  3  3  3  3  3   0   0
r3  4  4  4  4  4   0   0
r4  5  5  5  5  5   0   0
r5  0  0  0  0  0   0   0
r6  0  0  0  0  0   0   0

In [127]:
new_index=['r0','r1','r2','r3','r4','r5','r6','r7','r8']
ndf5 = df.reindex(new_index,fill_value=0) # 인덱스를 다시함(new_index,없는 값은 0으로 채움)
ndf5

a  b  c  d  e
r0  1  1  1  1  1
r1  2  2  2  2  2
r2  3  3  3  3  3
r3  4  4  4  4  4
r4  5  5  5  5  5
r5  0  0  0  0  0
r6  0  0  0  0  0
r7  0  0  0  0  0
r8  0  0  0  0  0

In [132]:
# r5~r8 까지 삭제 후 출력하세요.
df1 = ndf5.drop(['r5','r6','r7','r8'])
df1

a  b  c  d  e
r0  1  1  1  1  1
r1  2  2  2  2  2
r2  3  3  3  3  3
r3  4  4  4  4  4
r4  5  5  5  5  5

In [140]:
df1_s = df1.sort_index(ascending=False) #행을 올림차순에 거짓을 줘서 내림차순으로
df1_s

a  b  c  d  e
r4  5  5  5  5  5
r3  4  4  4  4  4
r2  3  3  3  3  3
r1  2  2  2  2  2
r0  1  1  1  1  1

In [142]:
df1_c = df1.sort_values(by='c',ascending=False) #열을 정렬 c를 기준으로
df1_c

a  b  c  d  e
r4  5  5  5  5  5
r3  4  4  4  4  4
r2  3  3  3  3  3
r1  2  2  2  2  2
r0  1  1  1  1  1

In [152]:
df1_t = df1.transpose() # 행과 열을 바꾸는 함수
df1_r = df1_t.transpose()
df1_r

a  b  c  d  e
r0  1  1  1  1  1
r1  2  2  2  2  2
r2  3  3  3  3  3
r3  4  4  4  4  4
r4  5  5  5  5  5

In [295]:
# 과제
# 5행 5열 리스트, 배열, 사전 형태의 데이터를 데이터 프레임으로 변환
# 가급적 의미 있는 데이터
import numpy as np
import pandas as pd
np.random.seed(0)
ar1 = np.random.randint(2013,2022,size=(3))
ar_1 = pd.Series(ar1)
ar2 = np.random.randint(250,731,size=(3))
ar_2 = pd.Series(ar2)
ar3 = np.random.randint(1,51,size=(3))
ar_3 = pd.Series(ar3)
ar4 = np.random.randint(1980,2003,size=(3))
ar_4 = pd.Series(ar4)
ar5 = np.random.randint(1,5,size=(3))
ar_5 = pd.Series(ar5)
art = pd.concat([ar_1,ar_2,ar_3,ar_4,ar_5],axis=1)
li1 = [2017,530,18,1998,2]
li_1 = pd.Series(li1)
dic1 = {0:'2015',1:'430',2:'3',3:'1996',4:'4'}
dic_1 = pd.Series(dic1)
dl1 = pd.concat([li_1,dic_1],axis=1)
dl_1 = dl1.transpose()
dl_t = pd.concat([dl_1,art])
dl_t

0    1   2     3  4
0  2017  530  18  1998  2
1  2015  430   3  1996  4
0  2018  501  10  1998  1
1  2013  445  20  1984  1
2  2016  609  22  1986  1

In [317]:
# 위에서 변환한 데이터 프레임에서 데이터 변경, 삭제, 전치, 인덱스 등 처리를 한 후
# 다시 리스트, 배열, 사전 형태로 변환하여 출력하세요

dl_t.rename(columns={0:'학번',1:'학과코드',2:'개인번호',3:'출생연도',4:'학년'},inplace=True)
dl_t.reset_index(drop=True,inplace=True) # 기존 인덱스의 이전 값을 버리고 초기화
dt = dl_t.rename(index={0:1,1:2,2:3,3:4,4:5})
dt['데이터 추가'] = 0
dt.drop(['데이터 추가'],axis=1,inplace=True)
arr = dt.values
fli = dt.values.tolist()
dic1 = dt.to_dict()
print(arr,type(arr),'\n')
print(fli,type(fli),'\n')
print(dic1,type(dic1),'\n')

[[2017 530 18 1998 2]
 ['2015' '430' '3' '1996' '4']
 [2018 501 10 1998 1]
 [2013 445 20 1984 1]
 [2016 609 22 1986 1]] <class 'numpy.ndarray'> 

[[2017, 530, 18, 1998, 2], ['2015', '430', '3', '1996', '4'], [2018, 501, 10, 1998, 1], [2013, 445, 20, 1984, 1], [2016, 609, 22, 1986, 1]] <class 'list'> 

{'학번': {1: 2017, 2: '2015', 3: 2018, 4: 2013, 5: 2016}, '학과코드': {1: 530, 2: '430', 3: 501, 4: 445, 5: 609}, '개인번호': {1: 18, 2: '3', 3: 10, 4: 20, 5: 22}, '출생연도': {1: 1998, 2: '1996', 3: 1998, 4: 1984, 5: 1986}, '학년': {1: 2, 2: '4', 3: 1, 4: 1, 5: 1}} <class 'dict'> 



In [322]:
#과제
#데이터 형식 과제로 생성한 데이터프레임을 csv, excel, pickle, json파일로 저장하고 
#다시 읽어와서 출력하세요
dt.to_csv('dataset/wow.csv')
dt.to_excel('dataset/wow.xlsx')
dt.to_pickle('dataset/wow.pkl')
dt.to_json('dataset/wow.json')

r1 = pd.read_csv('dataset/wow.csv',index_col=0)
r2 = pd.read_excel('dataset/wow.xlsx',index_col=0)
r3 = pd.read_pickle('dataset/wow.pkl')
r4 = pd.read_json('dataset/wow.json')

print(r1,'\n')
print(r2,'\n')
print(r3,'\n')
print(r4,'\n')

     학번  학과코드  개인번호  출생연도  학년
1  2017   530    18  1998   2
2  2015   430     3  1996   4
3  2018   501    10  1998   1
4  2013   445    20  1984   1
5  2016   609    22  1986   1 

     학번  학과코드  개인번호  출생연도  학년
1  2017   530    18  1998   2
2  2015   430     3  1996   4
3  2018   501    10  1998   1
4  2013   445    20  1984   1
5  2016   609    22  1986   1 

     학번 학과코드 개인번호  출생연도 학년
1  2017  530   18  1998  2
2  2015  430    3  1996  4
3  2018  501   10  1998  1
4  2013  445   20  1984  1
5  2016  609   22  1986  1 

     학번  학과코드  개인번호  출생연도  학년
1  2017   530    18  1998   2
2  2015   430     3  1996   4
3  2018   501    10  1998   1
4  2013   445    20  1984   1
5  2016   609    22  1986   1 

