### 연산
- 행/열 인덱스를 기준으로 모든 원소를 정렬한다.
- 동일한 위치에 있는 원소끼리 일대일 대응시킨다.
- 일대일 대응이 되는 원소끼리 연산을 처리한다.

In [6]:
import pandas as pd
st1 = pd.Series({'국어':100,'영어':80,'수학':90})
st2 = pd.Series({'수학':80,'국어':90,'영어':80})
print(st1)
print(st2)

국어    100
영어     80
수학     90
dtype: int64
수학    80
국어    90
영어    80
dtype: int64


In [7]:
add = st1 + st2
sub = st1 - st2
mul = st1 * st2
div = round((st1 / st2),2)
print(add)

국어    190
수학    170
영어    160
dtype: int64


In [8]:
df = pd.concat([add,sub,mul,div],axis=1)
df

0   1     2     3
국어  190  10  9000  1.11
수학  170  10  7200  1.12
영어  160   0  6400  1.00

In [11]:
# df의 컬럼이름을 add,sub,mul,div으로 변경하여 출력하세요
df.rename(columns={0:'add',1:'sub',2:'mul',3:'div'},inplace=True)
# df.columns = ['add','sub','mul','div']
df

add  sub   mul   div
국어  190   10  9000  1.11
수학  170   10  7200  1.12
영어  160    0  6400  1.00

In [34]:
import pandas as pd
import numpy as np
ds1 = pd.DataFrame(np.arange(12.).reshape((3,4)),columns=list('abcd'))
ds1

a    b     c     d
0  0.0  1.0   2.0   3.0
1  4.0  5.0   6.0   7.0
2  8.0  9.0  10.0  11.0

In [32]:
a = np.arange(10)
print(a)
a.reshape(5,2) #a를 5행 2열의 배열로 만든다

[0 1 2 3 4 5 6 7 8 9]


array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [31]:
a = np.arange(12)
print(a)
b = a.reshape(2,2,3) # reshape는 차원도 바꿀 수 있다.
c = b.reshape(4,3)
c

[ 0  1  2  3  4  5  6  7  8  9 10 11]


array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [38]:
df2 = pd.DataFrame(np.arange(20.).reshape((4,5)),columns=list('abcde'))
df2



a     b     c     d     e
0   0.0   1.0   2.0   3.0   4.0
1   5.0   6.0   7.0   8.0   9.0
2  10.0  11.0  12.0  13.0  14.0
3  15.0  16.0  17.0  18.0  19.0

In [51]:
print(ds1 + df2)
print(ds1 - df2)
print(ds1 * df2)
print(ds1 / df2)

      a     b     c     d   e
0   0.0   2.0   4.0   6.0 NaN
1   9.0  11.0  13.0  15.0 NaN
2  18.0  20.0  22.0  24.0 NaN
3   NaN   NaN   NaN   NaN NaN
     a    b    c    d   e
0  0.0  0.0  0.0  0.0 NaN
1 -1.0 -1.0 -1.0 -1.0 NaN
2 -2.0 -2.0 -2.0 -2.0 NaN
3  NaN  NaN  NaN  NaN NaN
      a     b      c      d   e
0   0.0   1.0    4.0    9.0 NaN
1  20.0  30.0   42.0   56.0 NaN
2  80.0  99.0  120.0  143.0 NaN
3   NaN   NaN    NaN    NaN NaN
     a         b         c         d   e
0  NaN  1.000000  1.000000  1.000000 NaN
1  0.8  0.833333  0.857143  0.875000 NaN
2  0.8  0.818182  0.833333  0.846154 NaN
3  NaN       NaN       NaN       NaN NaN


In [53]:
add_data = ds1.add(df2,fill_value=0)
sub_data = ds1.sub(df2,fill_value=0)
mul_data = ds1.mul(df2,fill_value=0)
div_data = ds1.div(df2,fill_value=0)
print(add_data,'\n')
print(sub_data,'\n')
print(mul_data,'\n')
print(div_data,'\n') #0 나누기 0 = NaN값 나옴


      a     b     c     d     e
0   0.0   2.0   4.0   6.0   4.0
1   9.0  11.0  13.0  15.0   9.0
2  18.0  20.0  22.0  24.0  14.0
3  15.0  16.0  17.0  18.0  19.0 

      a     b     c     d     e
0   0.0   0.0   0.0   0.0  -4.0
1  -1.0  -1.0  -1.0  -1.0  -9.0
2  -2.0  -2.0  -2.0  -2.0 -14.0
3 -15.0 -16.0 -17.0 -18.0 -19.0 

      a     b      c      d    e
0   0.0   1.0    4.0    9.0  0.0
1  20.0  30.0   42.0   56.0  0.0
2  80.0  99.0  120.0  143.0  0.0
3   0.0   0.0    0.0    0.0  0.0 

     a         b         c         d    e
0  NaN  1.000000  1.000000  1.000000  0.0
1  0.8  0.833333  0.857143  0.875000  0.0
2  0.8  0.818182  0.833333  0.846154  0.0
3  0.0  0.000000  0.000000  0.000000  0.0 



In [58]:
1 / ds1 # inf값은 안나와야함 / ds1의 역수

a         b         c         d
0    inf  1.000000  0.500000  0.333333
1  0.250  0.200000  0.166667  0.142857
2  0.125  0.111111  0.100000  0.090909

In [61]:
#계산 인자를 뒤집어서 계산
ds1.rdiv(1) # 역수로 표현

a         b         c         d
0    inf  1.000000  0.500000  0.333333
1  0.250  0.200000  0.166667  0.142857
2  0.125  0.111111  0.100000  0.090909

In [65]:
#ds1
s1 = ds1.iloc[0] #ds1의 d 컬럼
s1

a    0.0
b    1.0
c    2.0
d    3.0
Name: 0, dtype: float64

In [66]:
ds1 - s1

a    b    c    d
0  0.0  0.0  0.0  0.0
1  4.0  4.0  4.0  4.0
2  8.0  8.0  8.0  8.0

In [71]:
s2 = ds1['d']
s2

0     3.0
1     7.0
2    11.0
Name: d, dtype: float64

In [73]:
ds1.sub(s2,axis=0)

a    b    c    d
0 -3.0 -2.0 -1.0  0.0
1 -3.0 -2.0 -1.0  0.0
2 -3.0 -2.0 -1.0  0.0

In [74]:
ds1

a    b     c     d
0  0.0  1.0   2.0   3.0
1  4.0  5.0   6.0   7.0
2  8.0  9.0  10.0  11.0

In [75]:
ds1.sub(s1,axis=1)

a    b    c    d
0  0.0  0.0  0.0  0.0
1  4.0  4.0  4.0  4.0
2  8.0  8.0  8.0  8.0

In [ ]:
#과제
#데이터 프레임 df1,df2를 생성하고 첫번째 행을 r1,r2에 첫번째 열을 c1,c2에 저장 한 후
#다음 연산을 수행하세요
-df1 + df2
-df1 - r1
-df1 - c1

In [ ]:
#rdiv():역수로 나누는 것
#덧셈, 곱셈, 뺄셈, 경우도 연산 사례 수행

In [96]:
df1 = pd.DataFrame(np.arange(25.).reshape((5,5)),columns=list('abcde'))
df2 = pd.DataFrame(np.arange(25.).reshape((5,5)),columns=list('abcde'))

r1 = df1.iloc[0]
r2 = df2.iloc[0]

c1 = df1['a']
c2 = df2['a']

print(df1 + df2)
print(df1 - r1)
print(df1 - c1)
print(df1.add(df2))
print(df1.sub(r1,axis=1)) #행
print(df1.sub(c1,axis=0)) #열

      a     b     c     d     e
0   0.0   2.0   4.0   6.0   8.0
1  10.0  12.0  14.0  16.0  18.0
2  20.0  22.0  24.0  26.0  28.0
3  30.0  32.0  34.0  36.0  38.0
4  40.0  42.0  44.0  46.0  48.0
      a     b     c     d     e
0   0.0   0.0   0.0   0.0   0.0
1   5.0   5.0   5.0   5.0   5.0
2  10.0  10.0  10.0  10.0  10.0
3  15.0  15.0  15.0  15.0  15.0
4  20.0  20.0  20.0  20.0  20.0
    a   b   c   d   e   0   1   2   3   4
0 NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN
1 NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN
2 NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN
3 NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN
4 NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN
      a     b     c     d     e
0   0.0   2.0   4.0   6.0   8.0
1  10.0  12.0  14.0  16.0  18.0
2  20.0  22.0  24.0  26.0  28.0
3  30.0  32.0  34.0  36.0  38.0
4  40.0  42.0  44.0  46.0  48.0
      a     b     c     d     e
0   0.0   0.0   0.0   0.0   0.0
1   5.0   5.0   5.0   5.0   5.0
2  10.0  10.0  10.0  10.0  10.0
3  15.0  15.0  15.0  15.0  15.0
4  20.0  20.